# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 262)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 18))
        self.label.setObjectName("label")
        self.excelPathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.excelPathLine.setGeometry(QtCore.QRect(140, 20, 421, 24))
        self.excelPathLine.setObjectName("excelPathLine")
        self.openExclePathButton = QtWidgets.QPushButton(self.centralwidget)
        self.openExclePathButton.setGeometry(QtCore.QRect(560, 20, 31, 26))
        self.openExclePathButton.setObjectName("openExclePathButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 141, 18))
        self.label_3.setObjectName("label_3")
        self.orgDirLine = QtWidgets.QLineEdit(self.centralwidget)
        self.orgDirLine.setGeometry(QtCore.QRect(140, 100, 421, 24))
        self.orgDirLine.setObjectName("orgDirLine")
        self.openOrgDirPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.openOrgDirPathButton.setGeometry(QtCore.QRect(560, 100, 31, 26))
        self.openOrgDirPathButton.setObjectName("openOrgDirPathButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 121, 18))
        self.label_4.setObjectName("label_4")
        self.openToPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.openToPathButton.setGeometry(QtCore.QRect(560, 140, 31, 26))
        self.openToPathButton.setObjectName("openToPathButton")
        self.toDirPathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.toDirPathLine.setGeometry(QtCore.QRect(140, 140, 421, 24))
        self.toDirPathLine.setObjectName("toDirPathLine")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 121, 20))
        self.label_5.setObjectName("label_5")
        self.columnLine = QtWidgets.QLineEdit(self.centralwidget)
        self.columnLine.setGeometry(QtCore.QRect(140, 60, 113, 24))
        self.columnLine.setObjectName("columnLine")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 60, 131, 18))
        self.label_6.setObjectName("label_6")
        self.yesFirstLine = QtWidgets.QRadioButton(self.centralwidget)
        self.yesFirstLine.setGeometry(QtCore.QRect(450, 60, 41, 22))
        self.yesFirstLine.setObjectName("yesFirstLine")
        self.noFirstLine = QtWidgets.QRadioButton(self.centralwidget)
        self.noFirstLine.setGeometry(QtCore.QRect(520, 60, 41, 22))
        self.noFirstLine.setObjectName("noFirstLine")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(480, 180, 111, 51))
        self.runButton.setObjectName("runButton")
        self.export_log_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_log_button.setEnabled(False)
        self.export_log_button.setGeometry(QtCore.QRect(350, 180, 111, 51))
        self.export_log_button.setObjectName("export_log_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Excel文件路径："))
        self.openExclePathButton.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "查找文件夹路径："))
        self.openOrgDirPathButton.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "移动目的路径："))
        self.openToPathButton.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "文件名所在列："))
        self.label_6.setText(_translate("MainWindow", "是否取第一行："))
        self.yesFirstLine.setText(_translate("MainWindow", "是"))
        self.noFirstLine.setText(_translate("MainWindow", "否"))
        self.runButton.setText(_translate("MainWindow", "运行"))
        self.export_log_button.setText(_translate("MainWindow", "导出复制记录"))
